account/urls.py
from django.urls import path
from . import views

app_name='account'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('<int:user_pk>/', views.profile, name='profile'),
]

feed/urls.py
from django.urls import path
from . import views


app_name='feed'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update', views.update, name='update'),
    path('<int:article_pk>/delete', views.delete, name='delete'),
    path('<int:article_pk>/comments/', views.comments, name='comments'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:hashtag_pk>/hashtag/', views.hashtag, name='hashtag'),
]


from django.conf.urls.static import static

from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

igclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('feed/', include('feed.urls')),
    path('account/', include('account.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail

# Create your models here.
class Hashtag(models.Model):
    content = models.TextField()

    def __str__(self):
        return self.content

class Article(models.Model):
    
    image = ProcessedImageField(
        blank=True,
        processors=[Thumbnail(900, 500)],
        format='JPEG',
        options={'quality': 100},
       
    )
    content = models.TextField()
    hashtags = models.ManyToManyField(Hashtag, related_name='tagged_articles', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')

class Comment(models.Model):
    article= models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')

feed/forms.py
from django import forms
from .models import Comment,Article


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ['image' , 'content',]
        read_only_fields = ['likeusers']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content',]
        read_only_fields = ['likeusers']

feed/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_http_methods
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .forms import CommentForm, ArticleForm
from .models import Article, Comment, Hashtag
from django.http import HttpResponseRedirect




# Create your views here.
def index(request):
    articles=Article.objects.order_by('-pk')
    paginator=Paginator(articles,3) # 숫자 -> 한 페이지에 몇개를 보여줄것인지
    page_number=request.GET.get('page')
    articles=paginator.get_page(page_number)
    context={
        'articles':articles
    }
    return render(request, 'feed/index.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST , request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            for word in article.content.split():
                if word.startswith('#'):
                    hashtag, created = Hashtag.objects.get_or_create(content = word)
                    article.hashtags.add(hashtag)
                
                        
            
            return redirect('feed:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'feed/create.html', context)



@require_http_methods(['GET'])
def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    commentform = CommentForm()
    comments = article.comment_set.all()
    paginator=Paginator(comments,3) # 숫자 -> 한 페이지에 몇개를 보여줄것인지
    page_number=request.GET.get('page')
    comments=paginator.get_page(page_number)
    context = {
        'commentform': commentform,
        'comments': comments,
        'article': article,
    }
    return render(request, 'feed/detail.html', context)


@require_http_methods(['GET', 'POST'])
def update(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    if request.method == 'POST': # update
        # Create a form to edit an existing Article, but use
        # POST data to populate the form.
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('feed:detail', article.pk)
    else: # edit
        # Creating a form to change an existing article.
        form = ArticleForm(instance=article)
    context = {
        'form': form,
        'article': article,
    }
    return render(request, 'feed/update.html', context)


@require_http_methods(['GET', 'POST'])
def delete(request,article_pk):
    article = get_object_or_404(Article,pk=article_pk)
    if request.method == "POST":
        
        article.delete()
        return redirect('feed:index')
    else:
        context={
            'article': article,
        }
        return render(request,'feed/delete.html',context)


@require_POST
def comments(request, article_pk):
    if request.user.is_authenticated:
        form = CommentForm(request.POST)
        article = get_object_or_404(Article, pk=article_pk)
        if form.is_valid:
            comments = form.save(commit=False)
            comments.user = request.user
            comments.article = article
            comments.save()
            return redirect('feed:detail', article.pk)
        else:
            context = {
                'form': form,
                'article': article,
            }
        return render(request, 'feed/detail.html', context)
    return redirect('account:login')

@require_POST
def like(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article,pk=article_pk)
        if request.user in article.like_users.all():
            article.like_users.remove(request.user)
            liked = False
        else:
            article.like_users.add(request.user)
            liked = True
        like_status = {
            'liked':liked,
            'like_count':article.like_users.count(),
        }
        return JsonResponse(like_status)
    else:
        return redirect('account:login')


def hashtag(request, hashtag_pk):
    tag = get_object_or_404(Hashtag,pk=hashtag_pk)
    articles = tag.tagged_articles.all()
    context = {
        'tag':tag,
        'articles':articles,
    }
    return render(request,'feed/hashtag.html',context)

        

feed/templates/feed/create.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center" style="font-family:fantasy;font-style:italic;">NEW PHOTOS!</h1>
<form action="" method ="POST" enctype="multipart/form-data"> 
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="작성완료">
</form>
{% endblock  %}

feed/templates/feed/delete.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center" style="font-family:fantasy;font-style:italic;">정말로 삭제하시겠습니까???</h3>
<div class="container d-flex justify-content-center">
<form action="{% url 'feed:delete' article.pk%}" method="POST">
{% csrf_token %}
<button type="submit" class="btn btn-secondary">삭제</button>
</form>
<button class="btn btn-secondary"><a href="{% url 'feed:detail' article.pk%}">아니요</a> </button>

</div>
{% endblock  %}

feed/templates/feed/detail.html
{% extends 'base.html' %} 
{% load extras %}

{% block content %}
<div class="container">
  <h1 class="text-center" style="font-family:fantasy;font-style:italic;"><b>#{{article.pk}}</b></h1>
  {% if article.image %}
  <img
    src="{{ article.image.url }}"
    alt="{{ article.image }}"
    class="col-12"
  />
  {% else %}
  <p><strong>이미지가 없습니다.</strong></p>
  {% endif %}
</div>

<div class="mb-2 pb-2">
  <a href="{% url 'account:profile' article.user.pk%}"
    ><b class="text-dark">{{article.user}}</b></a
  >
</div>
<div class="container border border-gray rounded">
  {{article.content|linebreaks|hashtag_link}}
</div>

<p>작성시간: {{article.created_at}}</p>

<hr />
<div class="justify-content-between d-flex">
  <div class="align-content-center">
    {% if request.user in article.like_users.all %}
      <form  class="like-form"  data-article-id="{{article.pk}}">
        <button class="btn btn-link" class="btn btn-link"><span style="font-size: 2em; color: Tomato" 
          ><i class="fas fa-heart" id="like"></i></span
      ></button class="btn btn-link" class="btn btn-link"></form>
      {% else %}
      <form  class="like-form" data-article-id="{{article.pk}}">
        <button class="btn btn-link">
          <span style="font-size: 2em; color: Tomato" 
          ><i class="far fa-heart" id="like"></i> </span
      >
    </button class="btn btn-link">
  </form>
      {% endif %}
    <button
      type="button"
      class="btn btn-link mb-3"
      data-toggle="modal"
      data-target="#like_users"
    >
    <span id="like-count-{{article.pk}}">{{article.like_users.all|length}}</span>명이 이 글을 좋아합니다.
    </button>
    <div
      class="modal fade"
      id="like_users"
      tabindex="-1"
      role="dialog"
      aria-labelledby="like_usersTitle"
      aria-hidden="true"
    >
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">
              좋아요를 누른 사람
            </h5>
            <button
              type="button"
              class="close"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {% for user in article.like_users.all %}
            <a href="{% url 'account:profile' user.pk%}"
              ><h5>{{user.username}}</h5></a
            >

            <hr />
            {% endfor %}
          </div>
          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-secondary"
              data-dismiss="modal"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="align-content-self">
  {% if article.user == request.user %}
    <a href="{% url 'feed:update' article.pk%}" class="btn btn-primary pt-2 pb-1 font-weight-bold" >수정하기</a>
    <a href="{% url 'feed:delete' article.pk%}" class="btn btn-primary pt-2 pb-1 font-weight-bold" >삭제하기</a>
  {% endif %}
  <a href="{% url 'feed:index'%}" class="btn btn-primary pt-2 pb-1 font-weight-bold" >목록으로</a>
  </div>
</div>

<h4><댓글 목록></h4>
<br />
{% for comment in comments %}

<p><b>{{comment.user}}</b>의 댓글 : {{comment.content}}</p>
<br />
{% endfor %}
<div class="pagination justify-content-center font-weight-bold">
  <span class="step-links">
    {% if comments.has_previous %}
    <a href="?page=1"> &laquo; </a>
    <a href="?page={{ comments.previous_page_number }}"
      >{{ comments.previous_page_number }}</a
    >
    {% endif %}
    <span class="current"> {{ comments.number }} </span>
    {% if comments.has_next %}
    <a href="?page={{ comments.next_page_number }}"
      >{{ comments.next_page_number }}</a
    >
    <a href="?page={{ comments.paginator.num_pages }}"> &raquo; </a>
    {% endif %}
  </span>
</div>
<form action="{% url 'feed:comments' article.pk%}" method="POST">
  {% csrf_token %} {{commentform}}
  <input type="submit" value="댓글작성" />
</form>


<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
  const forms = document.querySelectorAll('.like-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

 

  forms.forEach(function (form) {
    form.addEventListener('submit',function (event) {
      event.preventDefault()
      const articleId = event.target.dataset.articleId
      
      
      axios.post(`http://127.0.0.1:8000/feed/${articleId}/like/`,{},{
        headers: {'X-CSRFToken': csrftoken}
      })
        .then(function (res){
          const liked = res.data.liked
          const likeCount = res.data.like_count
          const likeCountSpan = document.querySelector(`#like-count-${articleId}`)
          likeCountSpan.innerText = likeCount
          
          const likeIcon =  document.querySelector(`#like`)
          if (liked){
            likeIcon.classList.remove('far')
            likeIcon.classList.add('fas')
          } else {
            likeIcon.classList.add('far')
            likeIcon.classList.remove('fas')}
          
          

        })
        .catch(function (err){
          console.log(err)
        })

    })
  })

  </script>

{% endblock %}

feed/templates/feed/hashtag.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center" style="font-family:fantasy;font-style:italic;"><b>{{tag.content}}</b></h1>
<div>
{% for article in articles %}

<p>내용 : {{article.content}}</p>
<hr>
{% endfor %}
</div>


{% endblock  %}

feed/templates/feed/index.html
{% extends 'base.html' %}

{% load extras %}
{% block content %}


<h1 class="text-center" style="font-family:fantasy;font-style:italic;"><b> CopyCAT</b><span style="color: dodgerblue"></span></h1>
{% for article in articles %}
<div class="container border border-black rounded">
  <a href="{% url 'feed:detail' article.pk%}">
    {% if article.image %}
    <img
      src="{{ article.image.url }}"
      alt="{{ article.image }}"
      class="col-12"
    />
    {% else %}
    <p><strong>이미지가 없습니다.</strong></p>
    {% endif %}
  </a>

  <div class="col-12">
    <button
      type="button"
      class="btn btn-link"
      data-toggle="modal"
      data-target="#like_users{{article.pk}}"
    >
      <span id="like-count-{{article.pk}}">{{article.like_users.all|length}}</span>명이 이 글을 좋아합니다.
    </button>
    <div
      class="modal fade"
      id="like_users{{article.pk}}"
      tabindex="-1"
      role="dialog"
      aria-labelledby="like_usersTitle"
      aria-hidden="true"
    >
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">
              좋아요를 누른 사람
            </h5>
            <button
              type="button"
              class="close"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {% for user in article.like_users.all %}
            <a href="{% url 'account:profile' user.pk%}"
              ><h5>{{user.username}}</h5></a
            >

            <hr />
            {% endfor %}
          </div>
          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-secondary"
              data-dismiss="modal"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="ml-4 pl-1">
      {% if request.user in article.like_users.all %}
      <form  class="like-form" data-article-id="{{article.pk}}"
        >
        <button class="btn btn-link" class="btn btn-link"><span style="font-size: 2em; color: Tomato" 
          ><i class="fas fa-heart" id="like-{{article.pk}}"></i></span
      ></button class="btn btn-link" class="btn btn-link"></form>
      {% else %}
      <form  class="like-form" data-article-id="{{article.pk}}"
        >
        <button class="btn btn-link">
          <span style="font-size: 2em; color: Tomato" 
          ><i class="far fa-heart" id="like-{{article.pk}}"></i> </span
      >
    </button class="btn btn-link">
  </form>
      {% endif %}
    </div>
    <div class="col-1 ml-0">
      <span style="font-size: 2em; color: black">
        <i
          class="far fa-comment"
          type="button"
          data-toggle="modal"
          data-target="#comments{{article.pk}}"
        ></i>
      </span>
    </div>
    <div
      class="modal fade"
      id="comments{{article.pk}}"
      tabindex="-1"
      role="dialog"
      aria-labelledby="commentsTitle"
      aria-hidden="true"
    >
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">댓글</h5>
            <button
              type="button"
              class="close"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {% for comment in article.comment_set.all %}
            <p><b>{{comment.user.username}}</b> {{comment.content}}</p>

            <hr />
            {% endfor %}
          </div>
          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-secondary"
              data-dismiss="modal"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-12">
    <p><a href="{% url 'account:profile' article.user.pk%}"><b>{{article.user}}</b></a> {{article.content|linebreaks|hashtag_link}}</p>
  </div>
</div>
<hr />
{% endfor %}
<div class="pagination justify-content-center font-weight-bold">
  <span class="step-links">
    {% if articles.has_previous %}
    <a href="?page=1" class="btn btn-primary"> &laquo; </a>
    <a href="?page={{ articles.previous_page_number }}" class="btn btn-primary"
      >{{ articles.previous_page_number }}</a
    >
    {% endif %}
    <span class="current btn btn-primary"> {{ articles.number }} </span>
    {% if articles.has_next %}
    <a href="?page={{ articles.next_page_number }}" class="btn btn-primary"
      >{{ articles.next_page_number }}</a
    >
    <a href="?page={{ articles.paginator.num_pages }}" class="btn btn-primary">
      &raquo;
    </a>
    {% endif %}
  </span>
</div>


<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
  const forms = document.querySelectorAll('.like-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

 

  forms.forEach(function (form) {
    form.addEventListener('submit',function (event) {
      event.preventDefault()
      const articleId = event.target.dataset.articleId
      
      
      axios.post(`http://127.0.0.1:8000/feed/${articleId}/like/`,{},{
        headers: {'X-CSRFToken': csrftoken}
      })
        .then(function (res){
          const liked = res.data.liked
          const likeCount = res.data.like_count
          const likeCountSpan = document.querySelector(`#like-count-${articleId}`)
          likeCountSpan.innerText = likeCount
          
          const likeIcon =  document.querySelector(`#like-${articleId}`)
          if (liked){
            likeIcon.classList.remove('far')
            likeIcon.classList.add('fas')
          } else {
            likeIcon.classList.add('far')
            likeIcon.classList.remove('fas')}
          
          

        })
        .catch(function (err){
          console.log(err)
        })

    })
  })

  </script>


{% endblock %}

feed/templates/feed/update.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center" style="font-family:fantasy;font-style:italic;">EDIT</h1>
<form action="" method ="POST" enctype="multipart/form-data"> 
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="수정완료">
</form>
{% endblock  %}