account/urls.py
from django.urls import path
from . import views

app_name='account'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('<int:user_pk>/', views.profile, name='profile'),
]

feed/urls.py
from django.urls import path
from . import views


app_name='feed'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update', views.update, name='update'),
    path('<int:article_pk>/delete', views.delete, name='delete'),
    path('<int:article_pk>/comments/', views.comments, name='comments'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:hashtag_pk>/hashtag/', views.hashtag, name='hashtag'),
]


from django.conf.urls.static import static

from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

igclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('feed/', include('feed.urls')),
    path('account/', include('account.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

igclone/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <title>Document</title>
    <script
      src="https://kit.fontawesome.com/c6d30f413c.js"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
  
    <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        
      
        <div class="navbar-nav align-items-center offset-5">
          <a class="nav-link active" href="{% url 'feed:index'%}">
            <span style="font-size: 3em; color: dodgerblue; font-family:fantasy;font-style:italic;">
              <i class="fas fa-cat"></i> <b>CopyCAT</b>
            </span>
          </a>
          
        </div>
        <div class="navbar-nav align-items-center ml-auto">
          {% if user.is_authenticated %}
          <a class="nav-link acive" href="{% url 'feed:create'%}">
            <span style="font-size: 3em; color: Mediumslateblue">
              <i class="fas fa-images"></i>
            </span>
          </a>
          <a class="nav-link" href="{% url 'account:profile' request.user.pk%}"
            >
            <span style="font-size: 3em; color: green">
              <i class="fas fa-user"></i>
            </span>
            </a
          >
          <form
            action="{% url 'account:logout'%}"
            method="POST"
            class="nav-link"
          >
            {% csrf_token %}
            <button class="btn btn-link text-black-50" type="submit">
              <span style="font-size: 3em; color: tomato">
               <i class="fas fa-sign-out-alt"></i>
              </span>
            </button>
          </form>
          {% else %}
          <a class="nav-link" href="{% url 'account:signup'%}"
            >
            <span style="font-size: 3em; color: blue">
               <i class="fas fa-user-plus"></i>
              </span>
            
            </a
          >
          <a class="nav-link" href="{% url 'account:login'%}"> <span style="font-size: 3em; color: blue">
               <i class="fas fa-sign-in-alt"></i>
              </span></a>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container mt-5">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://kit.fontawesome.com/c6d30f413c.js"
      crossorigin="anonymous"
    ></script>
  </body>
</html>